-- ============================================================
-- QUE LE PIDE EL CODIGO A LA BASE, Y QUE NO ESTA
--
-- NO CAMBIA NADA. Es una consulta de lectura. Devuelve la lista de columnas
-- que alguna pantalla del portal pide y que no existen en la base.
--
-- POR QUE EXISTE. `families.entrega_estimada` llevaba meses sin existir y la
-- pantalla de Entregas se veia vacia en vez de rota, en todos los eventos,
-- porque el codigo descartaba el error de Postgres. El esquema de este
-- proyecto se armo a mano en el dashboard, asi que nada compara lo que el
-- codigo pide contra lo que la base tiene. Esto lo compara.
--
-- COMO SE GENERO. Barriendo los 90 archivos del portal que consultan la base
-- y sacando cada par tabla/columna de los `.select()`, de los filtros
-- (`.eq`, `.order`, `.in`, ...) y de los objetos de `.insert()` y `.update()`.
-- Las relaciones anidadas de un select (`families(count)`, `events(nombre)`)
-- se atribuyen a su propia tabla, no a la de arriba.
--
-- LO QUE NO ALCANZA A VER, dicho sin maquillar:
--   - Claves calculadas o esparcidas (`...datos`) en insert y update: se
--     ignoran a proposito, no se adivinan.
--   - SQL escrito a mano dentro de funciones RPC.
--   - Columnas que existen en la base y el codigo nunca usa. Eso es lo
--     contrario y necesita otra consulta.
--
-- RESULTADO ESPERADO: cero filas. Cada fila que salga es una pantalla que
-- hoy esta rota o que reventaria en cuanto alguien la use.
-- ============================================================

with esperado(tabla, columna) as (values
  ('agreements','approved_at'),
  ('agreements','approved_by'),
  ('agreements','assigned_email'),
  ('agreements','contenido'),
  ('agreements','created_at'),
  ('agreements','created_by'),
  ('agreements','event_id'),
  ('agreements','family_id'),
  ('agreements','id'),
  ('agreements','nombre'),
  ('agreements','signed_at'),
  ('agreements','signed_ip'),
  ('agreements','signed_name'),
  ('agreements','signed_user_agent'),
  ('agreements','signing_token'),
  ('agreements','status'),
  ('agreements','type'),
  ('announcements','created_at'),
  ('announcements','cuerpo'),
  ('announcements','event_id'),
  ('announcements','id'),
  ('announcements','published'),
  ('announcements','tipo'),
  ('announcements','titulo'),
  ('blocks','audiencia'),
  ('blocks','contenido'),
  ('blocks','hinge_id'),
  ('blocks','id'),
  ('blocks','media_id'),
  ('blocks','orden'),
  ('blocks','rev'),
  ('blocks','tipo'),
  ('blocks','version_id'),
  ('checklist_items','completed'),
  ('checklist_items','event_id'),
  ('checklist_items','id'),
  ('compromisos','categoria'),
  ('compromisos','completado'),
  ('compromisos','completado_at'),
  ('compromisos','created_at'),
  ('compromisos','event_id'),
  ('compromisos','family_id'),
  ('compromisos','id'),
  ('compromisos','orden'),
  ('compromisos','texto'),
  ('documents','contenido'),
  ('documents','created_at'),
  ('documents','created_by'),
  ('documents','event_id'),
  ('documents','family_id'),
  ('documents','id'),
  ('documents','nombre'),
  ('documents','pdf_url'),
  ('documents','tipo'),
  ('documents','visibilidad'),
  ('event_content_blocks','activado_at'),
  ('event_content_blocks','activo'),
  ('event_content_blocks','contenido'),
  ('event_content_blocks','created_at'),
  ('event_content_blocks','event_id'),
  ('event_content_blocks','id'),
  ('event_content_blocks','orden'),
  ('event_content_blocks','tipo'),
  ('event_content_blocks','titulo'),
  ('event_tasks','created_at'),
  ('event_tasks','descripcion'),
  ('event_tasks','done'),
  ('event_tasks','done_at'),
  ('event_tasks','event_id'),
  ('event_tasks','fase'),
  ('event_tasks','id'),
  ('event_tasks','orden'),
  ('event_tasks','titulo'),
  ('event_team','bio_publica'),
  ('event_team','event_id'),
  ('event_team','foto_url'),
  ('event_team','id'),
  ('event_team','nombre'),
  ('event_team','notas_equipo'),
  ('event_team','orden'),
  ('event_team','rol'),
  ('events','capitulo'),
  ('events','ciudad'),
  ('events','contacto_capitulo'),
  ('events','costo_por_pareja'),
  ('events','es_prueba'),
  ('events','fecha_fin'),
  ('events','fecha_inicio'),
  ('events','id'),
  ('events','info_emergencia'),
  ('events','info_logistica'),
  ('events','info_que_llevar'),
  ('events','info_vestimenta'),
  ('events','n_parejas'),
  ('events','nombre'),
  ('events','notas_comerciales'),
  ('events','nube_url'),
  ('events','pais'),
  ('events','pipeline_status'),
  ('events','primer_deposito'),
  ('events','status'),
  ('events','ubicacion'),
  ('experience_versions','estado'),
  ('experience_versions','experience_id'),
  ('experience_versions','id'),
  ('families','checked_in_at'),
  ('families','email1'),
  ('families','email2'),
  ('families','entrega_estimada'),
  ('families','event_id'),
  ('families','fotos_nube_recibidas'),
  ('families','habitacion'),
  ('families','id'),
  ('families','nombre1'),
  ('families','nombre2'),
  ('families','nombre_familia'),
  ('families','notas'),
  ('families','status'),
  ('families','storybook_status'),
  ('families','user_id1'),
  ('families','user_id2'),
  ('families','video_fecha'),
  ('families','video_status'),
  ('intake_responses','anos_juntos'),
  ('intake_responses','como_se_conocieron'),
  ('intake_responses','event_id'),
  ('intake_responses','expectativas'),
  ('intake_responses','family_id'),
  ('intake_responses','hijos'),
  ('intake_responses','historia_pareja'),
  ('intake_responses','id'),
  ('intake_responses','legado'),
  ('intake_responses','mensaje_especial'),
  ('intake_responses','momentos_importantes'),
  ('intake_responses','notas_adicionales'),
  ('intake_responses','restricciones_alimentarias'),
  ('intake_responses','submitted_at'),
  ('intake_responses','submitted_by'),
  ('intake_responses','tienen_hijos'),
  ('intake_responses','valores'),
  ('itinerary_items','created_by'),
  ('itinerary_items','delayed'),
  ('itinerary_items','descripcion'),
  ('itinerary_items','dia'),
  ('itinerary_items','event_id'),
  ('itinerary_items','fecha'),
  ('itinerary_items','grupo'),
  ('itinerary_items','hora_fin'),
  ('itinerary_items','hora_inicio'),
  ('itinerary_items','id'),
  ('itinerary_items','notas_staff'),
  ('itinerary_items','orden'),
  ('itinerary_items','responsable'),
  ('itinerary_items','tipo'),
  ('itinerary_items','titulo'),
  ('itinerary_items','ubicacion'),
  ('itinerary_items','visibilidad'),
  ('media','bucket'),
  ('media','descargable'),
  ('media','id'),
  ('media','mime'),
  ('media','nombre'),
  ('media','path'),
  ('media','peso_bytes'),
  ('media','subido_por'),
  ('profiles','created_at'),
  ('profiles','email'),
  ('profiles','full_name'),
  ('profiles','id'),
  ('profiles','phone'),
  ('profiles','role'),
  ('push_subscriptions','endpoint'),
  ('push_subscriptions','event_id'),
  ('push_subscriptions','subscription'),
  ('push_subscriptions','user_id')
)
select e.tabla, e.columna
  from esperado e
  left join information_schema.columns c
    on c.table_schema = 'public'
   and c.table_name   = e.tabla
   and c.column_name  = e.columna
 where c.column_name is null
   and to_regclass('public.' || e.tabla) is not null
 order by e.tabla, e.columna;
